In [1]:
# Import Numpy
import numpy as np

# Import Matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

# SQL ALchemy 
from sqlalchemy import create_engine

# Import PyMySQL
import pymysql
pymysql.install_as_MySQLdb()

# Import Pandas 
import pandas as pd

In [2]:
# Loading CSV files
csv = "education_clean.csv"

In [3]:
education = pd.read_csv(csv)
education

,Unnamed: 0,Area,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19
0,0,United States,3001337.0,3039015.0,3128022.0,3144100.0,3149185.0,3169257.0,3168450.0,3187000.0,3225160.0,3253730.0,3297050.0,3299910.0
1,1,Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Northeast,552289.0,552973.0,556400.0,556611.0,554705.0,555202.0,546910.0,543080.0,548200.0,543580.0,547690.0,542370.0
3,3,Midwest,721220.0,717536.0,726844.0,718779.0,716072.0,713662.0,705550.0,708240.0,704100.0,708920.0,713060.0,715500.0
4,4,South,1031773.0,1068270.0,1104770.0,1119414.0,1121400.0,1138965.0,1145570.0,1162950.0,1192410.0,1217720.0,1247340.0,1255590.0
5,5,West,696055.0,700236.0,740008.0,749296.0,757008.0,761428.0,770420.0,772720.0,780450.0,783510.0,788960.0,786440.0
6,6,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,Alabama,41346.0,42082.0,43166.0,46035.0,45394.0,44233.0,44540.0,45420.0,45910.0,45490.0,45100.0,44400.0
8,8,Alaska,7855.0,8008.0,8245.0,8064.0,7989.0,7860.0,7720.0,7860.0,7690.0,7930.0,7940.0,7880.0
9,9,Arizona,61667.0,62374.0,61145.0,64472.0,63208.0,62208.0,66700.0,67200.0,67290.0,68190.0,66760.0,67240.0
10,10,Arkansas,28725.0,28057.0,28276.0,28205.0,28419.0,28928.0,29610.0,30350.0,30610.0,30960.0,30970.0,31010.0
11,11,California,374561.0,372310.0,404987.0,410467.0,418664.0,422125.0,424080.0,422830.0,424430.0,422200.0,426140.0,420520.0
12,12,Colorado,46082.0,47459.0,49321.0,50122.0,50087.0,50968.0,51310.0,51450.0,53470.0,54630.0,56300.0,57330.0
13,13,Connecticut,38419.0,34968.0,34495.0,38854.0,38681.0,38722.0,37860.0,37160.0,36660.0,36970.0,36440.0,36090.0
14,14,Delaware,7388.0,7839.0,8133.0,8043.0,8247.0,8070.0,8240.0,8390.0,8360.0,8540.0,8780.0,8690.0
15,15,District of Columbia,3352.0,3517.0,3602.0,3477.0,3860.0,3961.0,3880.0,3990.0,3950.0,3690.0,3820.0,3930.0
16,16,Florida,149046.0,153461.0,156130.0,155493.0,151964.0,158029.0,158440.0,163740.0,165090.0,170990.0,173290.0,176060.0
17,17,Georgia,83505.0,88003.0,91561.0,92338.0,90582.0,92416.0,94380.0,97420.0,99770.0,102660.0,104820.0,106090.0
18,18,Hawaii,11613.0,11508.0,10998.0,10716.0,11360.0,10790.0,11050.0,10760.0,10920.0,10930.0,11060.0,10580.0
19,19,Idaho,16567.0,16807.0,17793.0,17525.0,17568.0,17198.0,19120.0,18050.0,18180.0,18670.0,18940.0,19340.0
20,20,Illinois,135143.0,131670.0,139035.0,134956.0,139575.0,139228.0,137640.0,140520.0,136820.0,137340.0,138320.0,140550.0
21,21,Indiana,61901.0,63663.0,64551.0,66133.0,65667.0,66595.0,67560.0,66750.0,67190.0,67620.0,68200.0,69730.0
22,22,Iowa,34573.0,33926.0,34462.0,33853.0,33230.0,32548.0,32590.0,32450.0,32890.0,33160.0,33590.0,33200.0
23,23,Kansas,30737.0,30368.0,31642.0,31370.0,31898.0,31922.0,32150.0,31900.0,32950.0,33110.0,33610.0,33270.0
24,24,Kentucky,39339.0,41851.0,42664.0,43031.0,42642.0,42888.0,42400.0,42530.0,43850.0,43510.0,44380.0,44830.0
25,25,Louisiana,34401.0,35622.0,36573.0,35844.0,36675.0,37508.0,38180.0,37720.0,39080.0,39610.0,42120.0,40330.0
26,26,Maine,14350.0,14093.0,14069.0,13653.0,13473.0,13170.0,12730.0,12560.0,12750.0,12410.0,12340.0,12160.0
27,27,Maryland,59171.0,58304.0,59078.0,58745.0,58811.0,58896.0,58120.0,57650.0,57560.0,57130.0,58670.0,58010.0
28,28,Massachusetts,65197.0,65258.0,64462.0,64724.0,65157.0,66360.0,65200.0,65790.0,66980.0,66600.0,66880.0,66840.0
29,29,Michigan,115183.0,112742.0,110682.0,106017.0,105446.0,104210.0,102520.0,102020.0,100960.0,101010.0,101490.0,100500.0
30,30,Minnesota,60409.0,59729.0,59667.0,59357.0,57501.0,58255.0,56370.0,56800.0,56700.0,57420.0,57950.0,59100.0
31,31,Mississippi,24795.0,24505.0,25478.0,27321.0,26158.0,26502.0,26650.0,26260.0,27140.0,27510.0,28230.0,27360.0
32,32,Missouri,61717.0,62969.0,63994.0,62994.0,61313.0,61407.0,60900.0,60590.0,61480.0,61060.0,61250.0,60670.0
33,33,Montana,10396.0,10077.0,10075.0,9732.0,9750.0,9369.0,9470.0,9390.0,9420.0,9550.0,9300.0,9440.0
34,34,Nebraska,20035.0,19501.0,19370.0,20331.0,20464.0,20442.0,20580.0,20650.0,20960.0,21420.0,22150.0,22400.0
35,35,Nevada,18815.0,19904.0,20956.0,21182.0,21891.0,23038.0,22720.0,23040.0,22910.0,23390.0,23720.0,24200.0
36,36,New Hampshire,14982.0,14757.0,15034.0,14495.0,14426.0,14262.0,13790.0,13520.0,13670.0,13490.0,13340.0,13090.0
37,37,New Jersey,94994.0,95085.0,96225.0,95186.0,93819.0,96490.0,95220.0,95250.0,97300.0,96150.0,96510.0,96190.0
38,38,New Mexico,18264.0,17931.0,18595.0,19352.0,20315.0,19232.0,18590.0,19530.0,19640.0,19890.0,19520.0,19800.0
39,39,New York,176310.0,180917.0,183826.0,182759.0,180806.0,180351.0,178810.0,179110.0,181550.0,182620.0,186250.0,183100.0
40,40,North Carolina,83307.0,86712.0,88704.0,89892.0,93977.0,94339.0,96210.0,97020.0,101420.0,103800.0,108230.0,109450.0
41,41,North Dakota,6999.0,7232.0,7155.0,7156.0,6942.0,6900.0,6960.0,7040.0,7070.0,7140.0,7080.0,7330.0
42,42,Ohio,120758.0,122203.0,123437.0,124229.0,123135.0,122491.0,119520.0,120940.0,118870.0,120410.0,120010.0,119850.0
43,43,Oklahoma,37630.0,37219.0,38503.0,37744.0,37305.0,37033.0,37260.0,38420.0,39400.0,40280.0,40810.0,40700.0
44,44,Oregon,34949.0,35138.0,34671.0,34723.0,34261.0,33899.0,34440.0,34800.0,35240.0,35180.0,35100.0,35090.0
45,45,Pennsylvania,130298.0,130658.0,131182.0,130284.0,131733.0,129777.0,127200.0,123560.0,122970.0,120030.0,120760.0,119150.0
46,46,Rhode Island,10347.0,10028.0,9908.0,9724.0,9751.0,9579.0,9730.0,9900.0,10160.0,9250.0,9350.0,9960.0
47,47,South Carolina,35303.0,39114.0,40438.0,40708.0,41442.0,42246.0,41720.0,42650.0,44190.0,45110.0,46180.0,46340.0
48,48,South Dakota,8582.0,8123.0,8162.0,8248.0,8196.0,8239.0,7960.0,8140.0,7840.0,8130.0,8180.0,8090.0
49,49,Tennessee,57486.0,60368.0,62408.0,61862.0,62454.0,61323.0,60970.0,62010.0,62800.0,63470.0,63720.0,63590.0
50,50,Texas,252121.0,264275.0,280894.0,290470.0,292531.0,301390.0,304360.0,309280.0,320840.0,331390.0,341620.0,348740.0
51,51,Utah,28167.0,30463.0,31481.0,30888.0,31157.0,33186.0,33400.0,34070.0,35540.0,36780.0,37680.0,38220.0
52,52,Vermont,7392.0,7209.0,7199.0,6932.0,6859.0,6491.0,6360.0,6240.0,6170.0,6080.0,5810.0,5790.0
53,53,Virginia,77369.0,79651.0,81511.0,82895.0,83336.0,83279.0,83100.0,82680.0,84580.0,85770.0,88470.0,88100.0
54,54,Washington,61625.0,62764.0,66046.0,66453.0,65205.0,66066.0,66240.0,68200.0,69990.0,70430.0,70640.0,70930.0
55,55,West Virginia,17489.0,17690.0,17651.0,17311.0,17603.0,17924.0,17510.0,17460.0,17870.0,17830.0,18140.0,17970.0
56,56,Wisconsin,65183.0,65410.0,64687.0,64135.0,62705.0,61425.0,60810.0,60460.0,60380.0,61100.0,61230.0,60820.0
57,57,Wyoming,5494.0,5493.0,5695.0,5600.0,5553.0,5489.0,5590.0,5550.0,5740.0,5750.0,5870.0,5870.0

In [4]:
education = education[["Area", "2007-08", "2008-09", "2009-10", "2010-11", "2011-12", "2012-13", "2013-14", "2014-15", "2015-16", "2016-17", "2017-18", "2018-19"]]
education

,Area,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19
0,United States,3001337.0,3039015.0,3128022.0,3144100.0,3149185.0,3169257.0,3168450.0,3187000.0,3225160.0,3253730.0,3297050.0,3299910.0
1,Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Northeast,552289.0,552973.0,556400.0,556611.0,554705.0,555202.0,546910.0,543080.0,548200.0,543580.0,547690.0,542370.0
3,Midwest,721220.0,717536.0,726844.0,718779.0,716072.0,713662.0,705550.0,708240.0,704100.0,708920.0,713060.0,715500.0
4,South,1031773.0,1068270.0,1104770.0,1119414.0,1121400.0,1138965.0,1145570.0,1162950.0,1192410.0,1217720.0,1247340.0,1255590.0
5,West,696055.0,700236.0,740008.0,749296.0,757008.0,761428.0,770420.0,772720.0,780450.0,783510.0,788960.0,786440.0
6,State,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Alabama,41346.0,42082.0,43166.0,46035.0,45394.0,44233.0,44540.0,45420.0,45910.0,45490.0,45100.0,44400.0
8,Alaska,7855.0,8008.0,8245.0,8064.0,7989.0,7860.0,7720.0,7860.0,7690.0,7930.0,7940.0,7880.0
9,Arizona,61667.0,62374.0,61145.0,64472.0,63208.0,62208.0,66700.0,67200.0,67290.0,68190.0,66760.0,67240.0
10,Arkansas,28725.0,28057.0,28276.0,28205.0,28419.0,28928.0,29610.0,30350.0,30610.0,30960.0,30970.0,31010.0
11,California,374561.0,372310.0,404987.0,410467.0,418664.0,422125.0,424080.0,422830.0,424430.0,422200.0,426140.0,420520.0
12,Colorado,46082.0,47459.0,49321.0,50122.0,50087.0,50968.0,51310.0,51450.0,53470.0,54630.0,56300.0,57330.0
13,Connecticut,38419.0,34968.0,34495.0,38854.0,38681.0,38722.0,37860.0,37160.0,36660.0,36970.0,36440.0,36090.0
14,Delaware,7388.0,7839.0,8133.0,8043.0,8247.0,8070.0,8240.0,8390.0,8360.0,8540.0,8780.0,8690.0
15,District of Columbia,3352.0,3517.0,3602.0,3477.0,3860.0,3961.0,3880.0,3990.0,3950.0,3690.0,3820.0,3930.0
16,Florida,149046.0,153461.0,156130.0,155493.0,151964.0,158029.0,158440.0,163740.0,165090.0,170990.0,173290.0,176060.0
17,Georgia,83505.0,88003.0,91561.0,92338.0,90582.0,92416.0,94380.0,97420.0,99770.0,102660.0,104820.0,106090.0
18,Hawaii,11613.0,11508.0,10998.0,10716.0,11360.0,10790.0,11050.0,10760.0,10920.0,10930.0,11060.0,10580.0
19,Idaho,16567.0,16807.0,17793.0,17525.0,17568.0,17198.0,19120.0,18050.0,18180.0,18670.0,18940.0,19340.0
20,Illinois,135143.0,131670.0,139035.0,134956.0,139575.0,139228.0,137640.0,140520.0,136820.0,137340.0,138320.0,140550.0
21,Indiana,61901.0,63663.0,64551.0,66133.0,65667.0,66595.0,67560.0,66750.0,67190.0,67620.0,68200.0,69730.0
22,Iowa,34573.0,33926.0,34462.0,33853.0,33230.0,32548.0,32590.0,32450.0,32890.0,33160.0,33590.0,33200.0
23,Kansas,30737.0,30368.0,31642.0,31370.0,31898.0,31922.0,32150.0,31900.0,32950.0,33110.0,33610.0,33270.0
24,Kentucky,39339.0,41851.0,42664.0,43031.0,42642.0,42888.0,42400.0,42530.0,43850.0,43510.0,44380.0,44830.0
25,Louisiana,34401.0,35622.0,36573.0,35844.0,36675.0,37508.0,38180.0,37720.0,39080.0,39610.0,42120.0,40330.0
26,Maine,14350.0,14093.0,14069.0,13653.0,13473.0,13170.0,12730.0,12560.0,12750.0,12410.0,12340.0,12160.0
27,Maryland,59171.0,58304.0,59078.0,58745.0,58811.0,58896.0,58120.0,57650.0,57560.0,57130.0,58670.0,58010.0
28,Massachusetts,65197.0,65258.0,64462.0,64724.0,65157.0,66360.0,65200.0,65790.0,66980.0,66600.0,66880.0,66840.0
29,Michigan,115183.0,112742.0,110682.0,106017.0,105446.0,104210.0,102520.0,102020.0,100960.0,101010.0,101490.0,100500.0
30,Minnesota,60409.0,59729.0,59667.0,59357.0,57501.0,58255.0,56370.0,56800.0,56700.0,57420.0,57950.0,59100.0
31,Mississippi,24795.0,24505.0,25478.0,27321.0,26158.0,26502.0,26650.0,26260.0,27140.0,27510.0,28230.0,27360.0
32,Missouri,61717.0,62969.0,63994.0,62994.0,61313.0,61407.0,60900.0,60590.0,61480.0,61060.0,61250.0,60670.0
33,Montana,10396.0,10077.0,10075.0,9732.0,9750.0,9369.0,9470.0,9390.0,9420.0,9550.0,9300.0,9440.0
34,Nebraska,20035.0,19501.0,19370.0,20331.0,20464.0,20442.0,20580.0,20650.0,20960.0,21420.0,22150.0,22400.0
35,Nevada,18815.0,19904.0,20956.0,21182.0,21891.0,23038.0,22720.0,23040.0,22910.0,23390.0,23720.0,24200.0
36,New Hampshire,14982.0,14757.0,15034.0,14495.0,14426.0,14262.0,13790.0,13520.0,13670.0,13490.0,13340.0,13090.0
37,New Jersey,94994.0,95085.0,96225.0,95186.0,93819.0,96490.0,95220.0,95250.0,97300.0,96150.0,96510.0,96190.0
38,New Mexico,18264.0,17931.0,18595.0,19352.0,20315.0,19232.0,18590.0,19530.0,19640.0,19890.0,19520.0,19800.0
39,New York,176310.0,180917.0,183826.0,182759.0,180806.0,180351.0,178810.0,179110.0,181550.0,182620.0,186250.0,183100.0
40,North Carolina,83307.0,86712.0,88704.0,89892.0,93977.0,94339.0,96210.0,97020.0,101420.0,103800.0,108230.0,109450.0
41,North Dakota,6999.0,7232.0,7155.0,7156.0,6942.0,6900.0,6960.0,7040.0,7070.0,7140.0,7080.0,7330.0
42,Ohio,120758.0,122203.0,123437.0,124229.0,123135.0,122491.0,119520.0,120940.0,118870.0,120410.0,120010.0,119850.0
43,Oklahoma,37630.0,37219.0,38503.0,37744.0,37305.0,37033.0,37260.0,38420.0,39400.0,40280.0,40810.0,40700.0
44,Oregon,34949.0,35138.0,34671.0,34723.0,34261.0,33899.0,34440.0,34800.0,35240.0,35180.0,35100.0,35090.0
45,Pennsylvania,130298.0,130658.0,131182.0,130284.0,131733.0,129777.0,127200.0,123560.0,122970.0,120030.0,120760.0,119150.0
46,Rhode Island,10347.0,10028.0,9908.0,9724.0,9751.0,9579.0,9730.0,9900.0,10160.0,9250.0,9350.0,9960.0
47,South Carolina,35303.0,39114.0,40438.0,40708.0,41442.0,42246.0,41720.0,42650.0,44190.0,45110.0,46180.0,46340.0
48,South Dakota,8582.0,8123.0,8162.0,8248.0,8196.0,8239.0,7960.0,8140.0,7840.0,8130.0,8180.0,8090.0
49,Tennessee,57486.0,60368.0,62408.0,61862.0,62454.0,61323.0,60970.0,62010.0,62800.0,63470.0,63720.0,63590.0
50,Texas,252121.0,264275.0,280894.0,290470.0,292531.0,301390.0,304360.0,309280.0,320840.0,331390.0,341620.0,348740.0
51,Utah,28167.0,30463.0,31481.0,30888.0,31157.0,33186.0,33400.0,34070.0,35540.0,36780.0,37680.0,38220.0
52,Vermont,7392.0,7209.0,7199.0,6932.0,6859.0,6491.0,6360.0,6240.0,6170.0,6080.0,5810.0,5790.0
53,Virginia,77369.0,79651.0,81511.0,82895.0,83336.0,83279.0,83100.0,82680.0,84580.0,85770.0,88470.0,88100.0
54,Washington,61625.0,62764.0,66046.0,66453.0,65205.0,66066.0,66240.0,68200.0,69990.0,70430.0,70640.0,70930.0
55,West Virginia,17489.0,17690.0,17651.0,17311.0,17603.0,17924.0,17510.0,17460.0,17870.0,17830.0,18140.0,17970.0
56,Wisconsin,65183.0,65410.0,64687.0,64135.0,62705.0,61425.0,60810.0,60460.0,60380.0,61100.0,61230.0,60820.0
57,Wyoming,5494.0,5493.0,5695.0,5600.0,5553.0,5489.0,5590.0,5550.0,5740.0,5750.0,5870.0,5870.0

In [5]:
state_education = education[7:58]
state_education

,Area,2007-08,2008-09,2009-10,2010-11,2011-12,2012-13,2013-14,2014-15,2015-16,2016-17,2017-18,2018-19
7,Alabama,41346.0,42082.0,43166.0,46035.0,45394.0,44233.0,44540.0,45420.0,45910.0,45490.0,45100.0,44400.0
8,Alaska,7855.0,8008.0,8245.0,8064.0,7989.0,7860.0,7720.0,7860.0,7690.0,7930.0,7940.0,7880.0
9,Arizona,61667.0,62374.0,61145.0,64472.0,63208.0,62208.0,66700.0,67200.0,67290.0,68190.0,66760.0,67240.0
10,Arkansas,28725.0,28057.0,28276.0,28205.0,28419.0,28928.0,29610.0,30350.0,30610.0,30960.0,30970.0,31010.0
11,California,374561.0,372310.0,404987.0,410467.0,418664.0,422125.0,424080.0,422830.0,424430.0,422200.0,426140.0,420520.0
12,Colorado,46082.0,47459.0,49321.0,50122.0,50087.0,50968.0,51310.0,51450.0,53470.0,54630.0,56300.0,57330.0
13,Connecticut,38419.0,34968.0,34495.0,38854.0,38681.0,38722.0,37860.0,37160.0,36660.0,36970.0,36440.0,36090.0
14,Delaware,7388.0,7839.0,8133.0,8043.0,8247.0,8070.0,8240.0,8390.0,8360.0,8540.0,8780.0,8690.0
15,District of Columbia,3352.0,3517.0,3602.0,3477.0,3860.0,3961.0,3880.0,3990.0,3950.0,3690.0,3820.0,3930.0
16,Florida,149046.0,153461.0,156130.0,155493.0,151964.0,158029.0,158440.0,163740.0,165090.0,170990.0,173290.0,176060.0
17,Georgia,83505.0,88003.0,91561.0,92338.0,90582.0,92416.0,94380.0,97420.0,99770.0,102660.0,104820.0,106090.0
18,Hawaii,11613.0,11508.0,10998.0,10716.0,11360.0,10790.0,11050.0,10760.0,10920.0,10930.0,11060.0,10580.0
19,Idaho,16567.0,16807.0,17793.0,17525.0,17568.0,17198.0,19120.0,18050.0,18180.0,18670.0,18940.0,19340.0
20,Illinois,135143.0,131670.0,139035.0,134956.0,139575.0,139228.0,137640.0,140520.0,136820.0,137340.0,138320.0,140550.0
21,Indiana,61901.0,63663.0,64551.0,66133.0,65667.0,66595.0,67560.0,66750.0,67190.0,67620.0,68200.0,69730.0
22,Iowa,34573.0,33926.0,34462.0,33853.0,33230.0,32548.0,32590.0,32450.0,32890.0,33160.0,33590.0,33200.0
23,Kansas,30737.0,30368.0,31642.0,31370.0,31898.0,31922.0,32150.0,31900.0,32950.0,33110.0,33610.0,33270.0
24,Kentucky,39339.0,41851.0,42664.0,43031.0,42642.0,42888.0,42400.0,42530.0,43850.0,43510.0,44380.0,44830.0
25,Louisiana,34401.0,35622.0,36573.0,35844.0,36675.0,37508.0,38180.0,37720.0,39080.0,39610.0,42120.0,40330.0
26,Maine,14350.0,14093.0,14069.0,13653.0,13473.0,13170.0,12730.0,12560.0,12750.0,12410.0,12340.0,12160.0
27,Maryland,59171.0,58304.0,59078.0,58745.0,58811.0,58896.0,58120.0,57650.0,57560.0,57130.0,58670.0,58010.0
28,Massachusetts,65197.0,65258.0,64462.0,64724.0,65157.0,66360.0,65200.0,65790.0,66980.0,66600.0,66880.0,66840.0
29,Michigan,115183.0,112742.0,110682.0,106017.0,105446.0,104210.0,102520.0,102020.0,100960.0,101010.0,101490.0,100500.0
30,Minnesota,60409.0,59729.0,59667.0,59357.0,57501.0,58255.0,56370.0,56800.0,56700.0,57420.0,57950.0,59100.0
31,Mississippi,24795.0,24505.0,25478.0,27321.0,26158.0,26502.0,26650.0,26260.0,27140.0,27510.0,28230.0,27360.0
32,Missouri,61717.0,62969.0,63994.0,62994.0,61313.0,61407.0,60900.0,60590.0,61480.0,61060.0,61250.0,60670.0
33,Montana,10396.0,10077.0,10075.0,9732.0,9750.0,9369.0,9470.0,9390.0,9420.0,9550.0,9300.0,9440.0
34,Nebraska,20035.0,19501.0,19370.0,20331.0,20464.0,20442.0,20580.0,20650.0,20960.0,21420.0,22150.0,22400.0
35,Nevada,18815.0,19904.0,20956.0,21182.0,21891.0,23038.0,22720.0,23040.0,22910.0,23390.0,23720.0,24200.0
36,New Hampshire,14982.0,14757.0,15034.0,14495.0,14426.0,14262.0,13790.0,13520.0,13670.0,13490.0,13340.0,13090.0
37,New Jersey,94994.0,95085.0,96225.0,95186.0,93819.0,96490.0,95220.0,95250.0,97300.0,96150.0,96510.0,96190.0
38,New Mexico,18264.0,17931.0,18595.0,19352.0,20315.0,19232.0,18590.0,19530.0,19640.0,19890.0,19520.0,19800.0
39,New York,176310.0,180917.0,183826.0,182759.0,180806.0,180351.0,178810.0,179110.0,181550.0,182620.0,186250.0,183100.0
40,North Carolina,83307.0,86712.0,88704.0,89892.0,93977.0,94339.0,96210.0,97020.0,101420.0,103800.0,108230.0,109450.0
41,North Dakota,6999.0,7232.0,7155.0,7156.0,6942.0,6900.0,6960.0,7040.0,7070.0,7140.0,7080.0,7330.0
42,Ohio,120758.0,122203.0,123437.0,124229.0,123135.0,122491.0,119520.0,120940.0,118870.0,120410.0,120010.0,119850.0
43,Oklahoma,37630.0,37219.0,38503.0,37744.0,37305.0,37033.0,37260.0,38420.0,39400.0,40280.0,40810.0,40700.0
44,Oregon,34949.0,35138.0,34671.0,34723.0,34261.0,33899.0,34440.0,34800.0,35240.0,35180.0,35100.0,35090.0
45,Pennsylvania,130298.0,130658.0,131182.0,130284.0,131733.0,129777.0,127200.0,123560.0,122970.0,120030.0,120760.0,119150.0
46,Rhode Island,10347.0,10028.0,9908.0,9724.0,9751.0,9579.0,9730.0,9900.0,10160.0,9250.0,9350.0,9960.0
47,South Carolina,35303.0,39114.0,40438.0,40708.0,41442.0,42246.0,41720.0,42650.0,44190.0,45110.0,46180.0,46340.0
48,South Dakota,8582.0,8123.0,8162.0,8248.0,8196.0,8239.0,7960.0,8140.0,7840.0,8130.0,8180.0,8090.0
49,Tennessee,57486.0,60368.0,62408.0,61862.0,62454.0,61323.0,60970.0,62010.0,62800.0,63470.0,63720.0,63590.0
50,Texas,252121.0,264275.0,280894.0,290470.0,292531.0,301390.0,304360.0,309280.0,320840.0,331390.0,341620.0,348740.0
51,Utah,28167.0,30463.0,31481.0,30888.0,31157.0,33186.0,33400.0,34070.0,35540.0,36780.0,37680.0,38220.0
52,Vermont,7392.0,7209.0,7199.0,6932.0,6859.0,6491.0,6360.0,6240.0,6170.0,6080.0,5810.0,5790.0
53,Virginia,77369.0,79651.0,81511.0,82895.0,83336.0,83279.0,83100.0,82680.0,84580.0,85770.0,88470.0,88100.0
54,Washington,61625.0,62764.0,66046.0,66453.0,65205.0,66066.0,66240.0,68200.0,69990.0,70430.0,70640.0,70930.0
55,West Virginia,17489.0,17690.0,17651.0,17311.0,17603.0,17924.0,17510.0,17460.0,17870.0,17830.0,18140.0,17970.0
56,Wisconsin,65183.0,65410.0,64687.0,64135.0,62705.0,61425.0,60810.0,60460.0,60380.0,61100.0,61230.0,60820.0
57,Wyoming,5494.0,5493.0,5695.0,5600.0,5553.0,5489.0,5590.0,5550.0,5740.0,5750.0,5870.0,5870.0

In [6]:
# states=["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
# state_education.insert(0, "State", states)
# state_education

In [7]:
state_education = state_education.rename(columns={"Area": "Name", "2007-08": "2008", "2008-09": "2009", "2009-10": "2010", "2010-11": "2011", "2011-12": "2012", "2012-13": "2013", "2013-14": "2014", "2014-15": "2015", "2015-16": "2016", "2016-17": "2017", "2017-18": "2018", "2018-19": "2019"})
state_education.head()

,Name,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
7,Alabama,41346.0,42082.0,43166.0,46035.0,45394.0,44233.0,44540.0,45420.0,45910.0,45490.0,45100.0,44400.0
8,Alaska,7855.0,8008.0,8245.0,8064.0,7989.0,7860.0,7720.0,7860.0,7690.0,7930.0,7940.0,7880.0
9,Arizona,61667.0,62374.0,61145.0,64472.0,63208.0,62208.0,66700.0,67200.0,67290.0,68190.0,66760.0,67240.0
10,Arkansas,28725.0,28057.0,28276.0,28205.0,28419.0,28928.0,29610.0,30350.0,30610.0,30960.0,30970.0,31010.0
11,California,374561.0,372310.0,404987.0,410467.0,418664.0,422125.0,424080.0,422830.0,424430.0,422200.0,426140.0,420520.0

In [8]:
state_education = state_education.drop(['2019'], axis=1)
state_education.head()

,Name,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
7,Alabama,41346.0,42082.0,43166.0,46035.0,45394.0,44233.0,44540.0,45420.0,45910.0,45490.0,45100.0
8,Alaska,7855.0,8008.0,8245.0,8064.0,7989.0,7860.0,7720.0,7860.0,7690.0,7930.0,7940.0
9,Arizona,61667.0,62374.0,61145.0,64472.0,63208.0,62208.0,66700.0,67200.0,67290.0,68190.0,66760.0
10,Arkansas,28725.0,28057.0,28276.0,28205.0,28419.0,28928.0,29610.0,30350.0,30610.0,30960.0,30970.0
11,California,374561.0,372310.0,404987.0,410467.0,418664.0,422125.0,424080.0,422830.0,424430.0,422200.0,426140.0

In [9]:
state_education['Graduates 2008-2012'] = state_education[['2008','2009','2010','2011','2012']].mean(axis=1)
state_education.head()

,Name,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,Graduates 2008-2012
7,Alabama,41346.0,42082.0,43166.0,46035.0,45394.0,44233.0,44540.0,45420.0,45910.0,45490.0,45100.0,43604.6
8,Alaska,7855.0,8008.0,8245.0,8064.0,7989.0,7860.0,7720.0,7860.0,7690.0,7930.0,7940.0,8032.2
9,Arizona,61667.0,62374.0,61145.0,64472.0,63208.0,62208.0,66700.0,67200.0,67290.0,68190.0,66760.0,62573.2
10,Arkansas,28725.0,28057.0,28276.0,28205.0,28419.0,28928.0,29610.0,30350.0,30610.0,30960.0,30970.0,28336.4
11,California,374561.0,372310.0,404987.0,410467.0,418664.0,422125.0,424080.0,422830.0,424430.0,422200.0,426140.0,396197.8

In [10]:
state_education['Graduates 2013-2018'] = state_education[['2013','2014','2015','2016','2017']].mean(axis=1)
state_education.head()

,Name,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,Graduates 2008-2012,Graduates 2013-2018
7,Alabama,41346.0,42082.0,43166.0,46035.0,45394.0,44233.0,44540.0,45420.0,45910.0,45490.0,45100.0,43604.6,45118.6
8,Alaska,7855.0,8008.0,8245.0,8064.0,7989.0,7860.0,7720.0,7860.0,7690.0,7930.0,7940.0,8032.2,7812.0
9,Arizona,61667.0,62374.0,61145.0,64472.0,63208.0,62208.0,66700.0,67200.0,67290.0,68190.0,66760.0,62573.2,66317.6
10,Arkansas,28725.0,28057.0,28276.0,28205.0,28419.0,28928.0,29610.0,30350.0,30610.0,30960.0,30970.0,28336.4,30091.6
11,California,374561.0,372310.0,404987.0,410467.0,418664.0,422125.0,424080.0,422830.0,424430.0,422200.0,426140.0,396197.8,423133.0

In [11]:
state_education = state_education.drop(['2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018'], axis=1)
state_education.head()

             Name  Graduates 2008-2012  Graduates 2013-2018
7        Alabama               43604.6              45118.6
8         Alaska                8032.2               7812.0
9        Arizona               62573.2              66317.6
10      Arkansas               28336.4              30091.6
11    California              396197.8             423133.0

In [12]:
state_education["Graduates Variance"] = state_education['Graduates 2013-2018'] - state_education['Graduates 2008-2012']

In [13]:
state_education.head()

,Name,Graduates 2008-2012,Graduates 2013-2018,Graduates Variance
7,Alabama,43604.6,45118.6,1514.0
8,Alaska,8032.2,7812.0,-220.2
9,Arizona,62573.2,66317.6,3744.4
10,Arkansas,28336.4,30091.6,1755.2
11,California,396197.8,423133.0,26935.2

In [14]:
state_education.to_csv("education_cleaner.csv", index=False)